import pkg from "../package.json";

function getVersion(): string {
  return pkg.version;
}
/**
 * コンパイル済み JS にヘッダーコメントを挿入する。
 * shebang (#!) がある場合はその行の直後に挿入。
 *
 * @param js - コンパイル済み JavaScript
 * @param version - バージョン文字列（省略時は package.json から取得）
 * @returns ヘッダー付き JavaScript
 */
export function addHeader(js: string, version?: string): string {
  const ver = version ?? getVersion();
  const header = `// Generated by NoShift.js ${ver}`;

  if (js.startsWith("#!")) {
    const newlineIndex = js.indexOf("\n");
    if (newlineIndex === -1) {
      // shebang のみでコードがない
      return js + "\n" + header + "\n";
    }
    const shebang = js.slice(0, newlineIndex + 1);
    const rest = js.slice(newlineIndex + 1);
    return shebang + header + "\n" + rest;
  }

  return header + "\n" + js;
}
