import { describe, it, expect } from "vitest";
import { addHeader } from "../header.js";

describe("addHeader()", () => {
  it("prepends header to normal code", () => {
    const js = 'console.log("Hello");';
    const result = addHeader(js, "1.0.0");
    expect(result).toBe('// Generated by NoShift.js 1.0.0\nconsole.log("Hello");');
  });

  it("inserts header after shebang line", () => {
    const js = '#!/usr/bin/env node\nconsole.log("Hello");';
    const result = addHeader(js, "1.0.0");
    expect(result).toBe(
      '#!/usr/bin/env node\n// Generated by NoShift.js 1.0.0\nconsole.log("Hello");',
    );
  });

  it("handles shebang-only file (no trailing newline)", () => {
    const js = "#!/usr/bin/env node";
    const result = addHeader(js, "2.0.0");
    expect(result).toBe("#!/usr/bin/env node\n// Generated by NoShift.js 2.0.0\n");
  });

  it("prepends header to empty string", () => {
    const result = addHeader("", "1.0.0");
    expect(result).toBe("// Generated by NoShift.js 1.0.0\n");
  });

  it("uses provided version string", () => {
    const result = addHeader("x", "0.12.1");
    expect(result).toContain("// Generated by NoShift.js 0.12.1");
  });
});

describe("compile() header integration", () => {
  // Dynamic import to avoid hoisting issues
  it("includes header by default", async () => {
    const { compile } = await import("../index.js");
    const result = compile("const x ^- 1;");
    expect(result.outputText).toMatch(/^\/\/ Generated by NoShift\.js /);
    expect(result.outputText).toContain("const x = 1;");
  });

  it("excludes header when noHeader is true", async () => {
    const { compile } = await import("../index.js");
    const result = compile("const x ^- 1;", { noHeader: true });
    expect(result.outputText).toBe("const x = 1;");
  });
});
